baseURL = "https://dfleischhacker.de/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "vim"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Daniel Fleischhacker"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Daniel Fleischhacker"
  email = ""
  description = "Landing Page"
  bio = "Engineering Manager | Software Engineer<br>[PhD in Computer Science](https://dblp.uni-trier.de/pid/53/7737.html)"
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/dfleischhacker"
    bitbucket = "https://bitbucket.org/dfleischhacker/"
    linkedIn = "https://www.linkedin.com/in/daniel-fleischhacker-0972b911"
